name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  SNAKEMAKE_OUTPUT_CACHE: snakemake_cache

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Formatting
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true

  Testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        type: ["rnaseq", "scrnaseq_10x_v3", "wgs"]
    needs:
      - Formatting
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Snakemake cache
        id: cache-sm
        uses: actions/cache@v3
        with:
          path: ${{ env.SNAKEMAKE_OUTPUT_CACHE }}
          key: ${{ matrix.type }}-sm
      - name: Install Mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge-pypy3
          miniforge-version: latest
          use-mamba: true
          python-version: 3.9
          channels: conda-forge,bioconda,nodefaults
          channel-priority: strict
      - name: Install snakemake
        run: mamba install python=3.9 snakemake
      - name: Run pipeline
        run: |
          mkdir -p ${{ env.SNAKEMAKE_OUTPUT_CACHE }}
          export SNAKEMAKE_OUTPUT_CACHE=$(pwd)/${{ env.SNAKEMAKE_OUTPUT_CACHE }}
          snakemake ${{ matrix.type }} \
          --use-conda \
          --show-failed-logs \
          --cores 2 \
          --cache \
          --conda-cleanup-pkgs cache \
          --all-temp
