name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  SNAKEMAKE_OUTPUT_CACHE: snakemake_cache

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Formatting
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true

  Testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        type: ["rnaseq", "scrnaseq_10x_v3", "wgs", "longrnaseq"]
    needs:
      - Formatting
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install Mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          use-mamba: true
          python-version: 3.12
          channels: conda-forge,bioconda,nodefaults
          channel-priority: strict
          environment-file: conda.yaml
      - name: Run pipeline
        run: |
          snakemake ${{ matrix.type }} \
          --use-conda \
          --show-failed-logs \
          --cores 2 \
          --conda-cleanup-pkgs cache \
          --all-temp
